Strategic9/weekly-menu-assistant

next.config.js, package.json, src/pages/dishes/index.tsx, src/pages/index.tsx, src/services/api.ts
I'm working on adding a test environment, this is part of that process.
We need a test environment to see the new changes online, not only on our machines.
=> Configuring the project to run Previews on Netlify

package.json, yarn.lock
Added and configured the Commitizen tool
Commitizen is a great tool to make the commit process more human friendly. With Commitizen we can communicate better the changes we add to the codebase.
https://trello.com/c/R9ie8mFc/40-add-commitizen-into-the-front
=> feat(commitizen): adding the commitizen tool to the project

public/assets/profile.svg, src/components/Alert.tsx, src/components/Header/Logo.tsx, src/components/Header/Profile.tsx, src/components/Header/ProfileDropdown.tsx, src/components/Header/index.tsx, src/pages/_app.tsx, src/pages/categories/add.tsx, src/pages/index.tsx, src/pages/page-wrapper.tsx, src/pages/signup.tsx, src/services/localstorage.ts, src/styles/theme.ts, yarn.lock
Added different things in the frontend to improve the experience. If you want to check all the things added, please go to the Trello task linked in this PR.
there were items missing in some parts of the code.
https://trello.com/c/vwcSpr8K/42-frontend-improvements
=> feat(auth and dashboard): improved multiple things in the frontend

next.config.js, src/components/Form/DatePicker/WeekPicker.tsx, src/components/Header/ProfileDropdown.tsx, src/components/MenuItems/index.tsx, src/components/Options/index.tsx, src/pages/dishes/upload-dish.tsx, src/pages/index.tsx, src/pages/menu/index.tsx, src/pages/menu/upload-menu.tsx, src/services/api.ts, src/services/hooks/useDishes.ts, src/services/hooks/useGroceries.ts, src/services/hooks/useMenu.ts, src/services/utils.ts
=> add upload dish view

.gitignore, src/components/Dish.tsx, src/pages/dishes/view/[dish].tsx, src/services/hooks/useDishes.ts, src/services/utils.ts, src/styles/theme.ts
=> Adding dish detail page

src/__tests__/SideBar.test.tsx, src/components/Dish.tsx, src/components/Form/DishForm.tsx, src/components/Form/EditIngredient.tsx, src/components/Form/FileUpload.tsx, src/components/Form/GroceryForm.tsx, src/components/Form/SearchDish.tsx, src/components/Form/SearchIngredient.tsx, src/components/Form/Select.tsx, src/components/Header/ProfileDropdown.tsx, src/components/Header/SearchBox.tsx, src/components/MenuItems/index.tsx, src/components/Options/index.tsx, src/components/Sidebar/SidebarNav.tsx, src/components/Sidebar/index.tsx, src/pages/categories/add.tsx, src/pages/categories/edit/[category].tsx, src/pages/categories/index.tsx, src/pages/dishes/add.tsx, src/pages/dishes/edit/[dish].tsx, src/pages/dishes/index.tsx, src/pages/dishes/upload-dish.tsx, src/pages/groceries/add.tsx, src/pages/groceries/edit/[grocery].tsx, src/pages/groceries/index.tsx, src/pages/index.tsx, src/pages/menu/history.tsx, src/pages/menu/index.tsx, src/pages/shop-list.tsx, src/pages/signup.tsx
=> Feature/translate menus/strings to swedish

src/components/Pagination/PaginationItem.tsx, src/components/Pagination/index.tsx, src/pages/categories/index.tsx, src/pages/dishes/index.tsx, src/pages/groceries/index.tsx, src/services/hooks/useCategories.ts, src/services/hooks/useDishes.ts
Fixed the pagination issues
Fixed the pagination issues in categories, dishes and groceries
It solves the pagination issue
https://trello.com/c/1QgXXnv6/81-fix-pagination-issues
=> Fix_pagination

src/components/Form/SearchDish.tsx, src/components/MenuItems/index.tsx, src/components/Options/index.tsx, src/pages/menu/index.tsx, src/services/utils.ts
Added some styles to the dish when it appears on the searchbar
It was awful before.
https://trello.com/b/ExIesDSA/food-and-shoping-assistant
=> Improve dish component on searchbar

src/components/AlertDialog.tsx, src/pages/_app.tsx, src/pages/menu/history.tsx, src/pages/menu/index.tsx
YES and No are not Swedish words.
https://trello.com/c/YTJeyVg1/76-translate-system-to-swedish
=> Moved the error alert to MIDDLE and added missed translations

src/components/Form/GroceryForm.tsx, src/components/Form/SearchIngredient.tsx, src/components/Header/Profile.tsx, src/pages/categories/index.tsx, src/pages/groceries/add.tsx, src/pages/shop-list.tsx, src/services/hooks/useMenu.ts
=> Fix_shopping_list

src/components/Form/DishForm.tsx, src/components/Form/EditIngredient.tsx, src/components/Form/GroceryForm.tsx, src/components/Form/Input.tsx, src/components/Form/Select.tsx, src/pages/dishes/add.tsx, src/pages/dishes/edit/[dish].tsx, src/pages/dishes/view/[dish].tsx, src/pages/groceries/add.tsx, src/pages/groceries/edit/[grocery].tsx, src/pages/shop-list.tsx, src/services/hooks/useGroceries.ts, src/services/hooks/useMeasurementUnit.ts, src/services/hooks/useMenu.ts
Added the measurement unit field to the dish form.
The ingredients of dishes must have a measurement unit linked to.
https://trello.com/c/fpoliC5N/87-add-measurement-unit-to-dish
updating the measurement unit is not working yet and will be fixed in the backend.
=> Measurement unit add edit dish

src/pages/menu/index.tsx
=> add specific message when not enough dishes on generate menu

src/pages/index.tsx
=> Login response including user id

src/components/Pagination/index.tsx
Pagination was broken
https://trello.com/c/jKIFPSmC/100-pagination-is-not-working-on-groceries-and-dishes
- [ x] Yes, the task is completed and it is working as expected
=> Fix pagination not working on groceries and dishes

package.json, src/components/Header/ProfileDropdown.tsx, src/pages/_app.tsx, src/pages/api/auth/[...nextauth].ts, src/pages/index.tsx, src/pages/signup.tsx
=> adding new Google signIn

src/components/Dish.tsx, src/components/Sidebar/SidebarNav.tsx, src/cotexts/AppContext.tsx, src/pages/_app.tsx, src/pages/categories/index.tsx, src/pages/dishes/view/[dish].tsx, src/pages/groceries/index.tsx, src/services/hooks/useUser.ts
Added new rules to hide parts of the page if the user is not an admin.
There were information open to the public that should only be available to the admin
https://trello.com/c/PBigq3uX/148-user-and-admin-role
=> Adding role validations

.eslintrc.json, src/__tests__/Header.test.tsx, src/__tests__/SideBar.test.tsx, src/components/Sidebar/SidebarNav.tsx, src/pages/admin/index.tsx, src/pages/admin/user/[user].tsx
=> Admin page bugfix

src/components/AlertDialog.tsx, src/pages/shop-list/shopListDetails.tsx
=> Fixed ingredients list not updating when deleting an ingredient

src/pages/shop-list/shopListDetails.tsx, src/services/hooks/useMenu.ts
=> Make shop list page not brake if you delete item and then add it again

src/pages/shop-list/shopListDetails.tsx, src/services/hooks/useMenu.ts
=> Undo fix shopping list not updating after changed in weekly menu

src/components/MenuItems/index.tsx, src/pages/menu/index.tsx
- [ x] Yes, the task is completed and it is working as expected
=> Make draggable work for days with no menuDish.id

src/components/Form/GroceryForm.tsx, src/components/Form/SearchIngredient.tsx, src/pages/groceries/edit/[grocery].tsx, src/pages/shop-list/shopListDetails.tsx, src/services/hooks/useGroceries.ts
- [ x] Yes, the task is completed and it is working as expected
=> Select unit when item is added to shopping list

package-lock.json, src/components/Form/DishForm.tsx, src/components/Form/GroceryForm.tsx, src/components/Form/SearchDish.tsx, src/components/Form/Select.tsx, src/services/hooks/useDishes.ts, src/services/hooks/useGroceries.ts
=> Add suggestion of dishes when you try to add new one after deleting dish

.gitignore, src/pages/menu/history.tsx, src/pages/menu/index.tsx
=> Sort menuhistory correct even if dishes have been moved in the menu

.gitignore, src/pages/menu/history.tsx, src/services/hooks/useMenu.ts
=> menu history fix

src/components/Form/DishForm.tsx
=> Add ingredients to dish then choose one to be main ingredient

src/components/Dish.tsx, src/components/Header/Profile.tsx, src/components/Header/ProfileDropdown.tsx, src/components/Sidebar/SidebarNav.tsx, src/contexts/SidebarDrawerContext.tsx, src/contexts/UserContext.tsx, src/pages/_app.tsx, src/pages/categories/index.tsx, src/pages/dishes/view/[dish].tsx, src/pages/groceries/index.tsx, src/pages/index.tsx, src/pages/menu/index.tsx, src/pages/page-wrapper.tsx, src/pages/signup.tsx
=> Improve security when login in by not storing user credentials i local storage

src/pages/menu/index.tsx
Reverts Strategic9/weekly-menu-assistant#88
=> Revert "Feature/generate menu btn even if week as dishes"

src/pages/menu/index.tsx, src/services/hooks/useMenu.ts
=> Display empty days for empty menu

src/contexts/UserContext.tsx, src/pages/menu/index.tsx, src/pages/page-wrapper.tsx, src/services/hooks/useMenu.ts
=> Display menu based on the user.
